spring:
  application:
    name: spring-openai-demo
#  ai:
#    anthropic:
#      api-key: ${ANTHROPIC_API_KEY}
#  ai:
#    google:
#      genai:
#        chat:
#          options:
#            model: gemini-2.5-flash
#        api-key: ${GOOGLE_GEN_KEY}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'